import img1 from "../assets/payu/card1.png"
import img2 from "../assets/payu/card2.png"

export const Connectors = [
  {
    img1: img1,
    type: "JT772",
    price: "0.44 / kWh",
    slot: "Slot 1 • AC • 44.4 kW",
    slot1: "Slot 1",
    slot2: "AC",
    slot3: "44.4 kW",
    sessionFee: "0.98",
    sessionFee1: "Session Fee",
    parkingFee: "Parking Fee  1.05",
    available: true,
    status: "Available",
  },
  {
    img1: img2,
    type: "JT772",
    price: "0.44 / kWh",
    slot: "Slot 1: AC: 44.4 kW",
    slot1: "Slot 1",
    slot2: "AC",
    slot3: "44.4 kW",
    sessionFee: "0.98",
    sessionFee1: "Session Fee",
    parkingFee: "Parking Fee  1.05",
    available: true,
    status: "Available",
  },
  {
    img1: img1,
    type: "JT772",
    price: "0.44 / kWh",
    slot: "Slot 1: AC: 44.4 kW",
    slot1: "Slot 1",
    slot2: "AC",
    slot3: "44.4 kW",
    sessionFee: "0.98",
    sessionFee1: "Session Fee",
    parkingFee: "Parking Fee  1.05",
    available: true,
    status: "Available",
  },
  {
    img1: img1,
    type: "JT772",
    price: "0.44 / kWh",
    slot: "Slot 1: AC: 44.4 kW",
    slot1: "Slot 1",
    slot2: "AC",
    slot3: "44.4 kW",
    sessionFee: "0.98",
    sessionFee1: "Session Fee",
    parkingFee: "Parking Fee  1.05",
    available: false,
    status: "In use",
  },
  {
    img1: img1,
    type: "CCS2",
    price: "0.44 / kWh",
    slot: "Slot 2: DC: 44.4 kW",
    slot1: "Slot 1",
    slot2: "AC",
    slot3: "44.4 kW",
    sessionFee: "0.98",
    sessionFee1: "Session Fee",
    parkingFee: "Parking Fee  1.25",
    available: true,
    status: "Fast charger",
  },
  {
    img1: img1,
    type: "CCS2",
    price: "0.44 / kWh",
    slot: "Slot 2: DC: 44.4 kW",
    slot1: "Slot 1",
    slot2: "AC",
    slot3: "44.4 kW",
    sessionFee: "0.98",
    sessionFee1: "Session Fee",
    parkingFee: "Parking Fee  1.25",
    available: false,
    status: "In use",
  },
  {
    img1: img1,
    type: "CCS2",
    price: "0.44 / kWh",
    slot: "Slot 2: DC: 44.4 kW",
    slot1: "Slot 1",
    slot2: "AC",
    slot3: "44.4 kW",
    sessionFee: "0.98",
    sessionFee1: "Session Fee",
    parkingFee: "Parking Fee  1.25",
    available: false,
    status: "Faulted",
  },
  {
    img1: img1,
    type: "CCS2",
    price: "0.44 / kWh",
    slot: "Slot 2: DC: 44.4 kW",
    slot1: "Slot 1",
    slot2: "AC",
    slot3: "44.4 kW",
    sessionFee: "0.98",
    sessionFee1: "Session Fee",
    parkingFee: "Parking Fee  1.25",
    available: false,
    status: "In use",
  },
]
